spring:
  application:
    name: STOCKMS
server:
  port: 4452
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4444/eureka/
    register-with-eureka: true
    fetch-registry: true